[geometry] Fix bikeshed preprocessing error.
Bikeshed was reporting:
  FATAL ERROR: No 'dfn' refs found for '… message topic …'.
because of the interaction of:
  Use <i> Autolinks: yes
with the boilerplate text generated for the mailing list information.

Adding "… message topic …" to "Ignored Terms:" fixes this.